#
# # Colors (Solarized Dark)
#
# # Default colors
# [colors.primary]
# background = '#002b36'
# foreground = '#839496'
#
# # Normal colors
# [colors.normal]
# black   = '#073642'
# red     = '#dc322f'
# green   = '#859900'
# yellow  = '#b58900'
# blue    = '#268bd2'
# magenta = '#d33682'
# cyan    = '#2aa198'
# white   = '#eee8d5'
#
# # Bright colors
# [colors.bright]
# black   = '#002b36'
# red     = '#cb4b16'
# green   = '#586e75'
# yellow  = '#657b83'
# blue    = '#839496'
# magenta = '#6c71c4'
# cyan    = '#93a1a1'
# white   = '#fdf6e3'
#

# Colors (Nord)

# Default colors
[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'

# Normal colors
[colors.normal]
black   = '#3B4252'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#88C0D0'
white   = '#E5E9F0'

# Bright colors
[colors.bright]
black   = '#4C566A'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#8FBCBB'
white   = '#ECEFF4'


# Colors (Nord)


[font]
size = 11.5

[font.bold]
#family = "JetBrainsMono Nerd Font Bold"

[font.bold_italic]
#family = "JetBrainsMono Nerd Font Bold Italic"

[font.italic]
#family = "JetBrainsMono Nerd Font Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "G"
mods = "Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[scrolling]
history = 5000
multiplier = 3

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "full"
dynamic_title = false
#title = "ArchBang Terminal..."

[window.padding]
x = 10
y = 10

[general]
ipc_socket = true

[terminal]

